server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: xc_cms
  freemarker:
    #关闭模版缓存，方便测试
    cache: false
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /

eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发ian，是否从Eureka中获取注册信息
    serviceUrl: #Eureka呵护端与Eureka服务端的加护地址，高可用状态配置对方的地址，单机状态配置自己(如果不配置则默认本机8761端口)
      #defaulZone: http://localhost:50101/eureka/
      defaulZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address: true #将自己的ip地主注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id