server:
  port: ${POST:50101} #服务端口(可配置格式，用于动态配置脚本启动)
spring:
  application:
    name: xc‐govern‐center
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发ian，是否从Eureka中获取注册信息
    serviceUrl: #Eureka呵护端与Eureka服务端的加护地址，高可用状态配置对方的地址，单机状态配置自己(如果不配置则默认本机8761端口)
      #defaulZone: http://localhost:50101/eureka/
      defaulZone: ${EUREKA_SERVER:http://eureka02:50102/eureka/}
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔(单位毫秒，默认是60*1000)
  instance:
    hostname: ${EUREKA_DOMAIN:eurela01} #Eureka服务的主机名